name: Build All Platforms

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and publish (e.g., v0.3.8-20250903203030)'
        required: false
        type: string
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04  # Use 22.04 for GLIBC 2.35 compatibility (works on 22.04 AND 24.04)
            target: x86_64-unknown-linux-gnu
            platform: linux-x64
          - os: ubuntu-22.04  # Use 22.04 for GLIBC 2.35 compatibility (works on 22.04 AND 24.04)
            target: aarch64-unknown-linux-gnu
            platform: linux-arm64
            use-cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            platform: windows-x64
          # Windows ARM64 is not well supported, commenting out for now
          # - os: windows-latest
          #   target: aarch64-pc-windows-msvc
          #   platform: windows-arm64
          - os: macos-13  # Intel runner for x86_64 builds
            target: x86_64-apple-darwin
            platform: macos-x64
          - os: macos-latest  # ARM runner for ARM builds
            target: aarch64-apple-darwin
            platform: macos-arm64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      
      - name: Verify cargo
        run: cargo -V || (source "$HOME/.cargo/env" && cargo -V)
          
      - name: Add Rust target (additional step for reliability)
        run: rustup target add ${{ matrix.target }}
          
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ matrix.target }}-
            ${{ runner.os }}-cargo-
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install workspace dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Windows build tools for vendored OpenSSL
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install strawberryperl nasm -y
          Start-Sleep -Seconds 5
          # Install missing Perl modules required by OpenSSL build
          cpan -T Locale::Maketext::Simple
          cpan -T IPC::Cmd
          cpan -T Params::Check

      - name: Configure vendored OpenSSL (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          echo "OPENSSL_STATIC=1"        >> $env:GITHUB_ENV
          echo "OPENSSL_VENDORED=1"      >> $env:GITHUB_ENV
          echo "OPENSSL_NO_VENDOR=0"     >> $env:GITHUB_ENV
          # Additional env vars to help with vendored build
          echo "PERL=$((Get-Command perl).Path)" >> $env:GITHUB_ENV
          
      - name: Install cross-compilation tools
        if: matrix.use-cross
        shell: bash
        run: |
          if command -v cross >/dev/null 2>&1; then
            echo "cross already installed: $(cross --version)"
          else
            cargo install cross --locked
          fi

      - name: Install ARM64 cross-compilation toolchain (Linux)
        if: matrix.target == 'aarch64-unknown-linux-gnu' && runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build frontend
        run: pnpm --filter frontend run build
      
      - name: Build Rust binaries (Windows)
        if: runner.os == 'Windows'
        env:
          LIBSQLITE3_SYS_USE_PKG_CONFIG: 0
          LIBZ_SYS_STATIC: 1
          OPENSSL_STATIC: 1
          SQLX_OFFLINE: true
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_API_ENDPOINT: ${{ secrets.POSTHOG_API_ENDPOINT }}
        run: cargo build --release --target ${{ matrix.target }}
        shell: bash

      - name: Build Rust binaries (non-Windows, cross)
        if: runner.os != 'Windows' && matrix.use-cross
        env:
          CROSS_CONTAINER_IN_CONTAINER: true
          OPENSSL_STATIC: 1
          DEP_OPENSSL_VENDORED: 1
          OPENSSL_VENDORED: 1
          OPENSSL_NO_VENDOR: 0
          LIBSQLITE3_SYS_USE_PKG_CONFIG: 0
          LIBSQLITE3_SYS_BUNDLED: 1
          LIBSQLITE3_SYS_STATIC: 1
          SQLX_OFFLINE: true
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_API_ENDPOINT: ${{ secrets.POSTHOG_API_ENDPOINT }}
        run: |
          # Force latest cross image with modern libclang (bypasses Cross.toml)
          cross build --release --target ${{ matrix.target }} --image ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest
        shell: bash

      - name: Build Rust binaries (non-Windows, native)
        if: runner.os != 'Windows' && !matrix.use-cross
        env:
          OPENSSL_STATIC: 1
          DEP_OPENSSL_VENDORED: 1
          OPENSSL_VENDORED: 1
          OPENSSL_NO_VENDOR: 0
          LIBSQLITE3_SYS_USE_PKG_CONFIG: 0
          LIBSQLITE3_SYS_BUNDLED: 1
          LIBSQLITE3_SYS_STATIC: 1
          LIBZ_SYS_STATIC: 1
          SQLX_OFFLINE: true
          POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
          POSTHOG_API_ENDPOINT: ${{ secrets.POSTHOG_API_ENDPOINT }}
        run: |
          cargo build --release --target ${{ matrix.target }}
        shell: bash
      
      - name: Package binaries (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "npx-cli/dist/${{ matrix.platform }}" | Out-Null

          Copy-Item "target/${{ matrix.target }}/release/forge-app.exe" "automagik-forge.exe"
          Compress-Archive -Path "automagik-forge.exe" -DestinationPath "automagik-forge.zip" -Force
          Move-Item "automagik-forge.zip" "npx-cli/dist/${{ matrix.platform }}/"
          Remove-Item "automagik-forge.exe"

          Copy-Item "target/${{ matrix.target }}/release/mcp_task_server.exe" "automagik-forge-mcp.exe"
          Compress-Archive -Path "automagik-forge-mcp.exe" -DestinationPath "automagik-forge-mcp.zip" -Force
          Move-Item "automagik-forge-mcp.zip" "npx-cli/dist/${{ matrix.platform }}/"
          Remove-Item "automagik-forge-mcp.exe"

      - name: Package binaries (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          mkdir -p npx-cli/dist/${{ matrix.platform }}

          cp target/${{ matrix.target }}/release/forge-app automagik-forge
          zip -q automagik-forge.zip automagik-forge
          mv automagik-forge.zip npx-cli/dist/${{ matrix.platform }}/
          rm automagik-forge

          cp target/${{ matrix.target }}/release/mcp_task_server automagik-forge-mcp
          zip -q automagik-forge-mcp.zip automagik-forge-mcp
          mv automagik-forge-mcp.zip npx-cli/dist/${{ matrix.platform }}/
          rm automagik-forge-mcp
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.platform }}
          path: npx-cli/dist/${{ matrix.platform }}/

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.tag != '')

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: npx-cli/dist/
          pattern: binaries-*
          merge-multiple: false
      
      - name: Reorganize artifacts
        run: |
          cd npx-cli/dist
          for dir in binaries-*; do
            platform=${dir#binaries-}
            # Ensure target directory exists
            mkdir -p $platform
            # Move all files (if any)
            if [ -d "$dir" ] && [ "$(ls -A $dir)" ]; then
              mv $dir/* $platform/ 2>/dev/null || true
            fi
            # Remove the now-empty directory
            rm -rf $dir
          done
          ls -la *
      
      - name: Determine NPM tag
        id: npm-tag
        run: |
          if [[ ${{ github.ref_name }} =~ -beta\. ]]; then
            echo "tag=beta" >> $GITHUB_OUTPUT
            echo "Publishing as beta version"
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
            echo "Publishing as latest version"
          fi
          
      - name: Publish to NPM
        run: |
          cd npx-cli
          npm publish --tag ${{ steps.npm-tag.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
